In [2]:
import numpy as np

## Decomposiçao LU

* Aparentemente objetivo dessa parte da matéria será entender e compreender as decomposiçoes para solucionar expressoes do tipo:

$Ax=b$

A ideia é transformar $Ax$ em LU, outra decomposiçao que veremos é a: $A = QR$


### Soluçoes para $Ax = b$

Podemos entender como $a_1x_1 + a_2x_2+a_3x_3+....+a_nx_n = b. pensando que A é uma matriz e X um vetor o qual queremos descobrir seus valores

se os $a_s$ forem li, X terá uma unica soluçao (pensar em coordenadas), com suas colunas li, invertiveis com det(a) $\neq$ 0
> Colunas base, b escrito nessa base, se li, a soluçao é unica

Atendendo assim as condiçoes:

1. det(a) $\neq$ 0
2. As colunas ou linhas de A sao li
3. Existe uma matriz inveras $A^{-1}$ tal que $AA^{-1}=A^{-1}A = I$
4. C(A) = $\R^n$
5. N(A) = {0}


### LU
* L (low) = matriz triangular inferior
* U (Up) = matriz triangular superior

Assim

$A_x = b <=> (L*U)x = b  <=> L*(UX) = B$

In [7]:
def lu_decomposition(A):
    # recebe uma matriz A e retorna a decomposição LU de A
    # iniciaremos as matrizes L e U com as dimensoes de A, nessa decomposiçao, L possui diagonal unitária por padrão

    n = A.shape[0] # número de linhas de A (matriz quadrada)
    L = np.eye(n) # inicia como matriz identidade
    U = np.zeros((n, n)) # inicia como matriz nula


    for i in range(n): # para cada linha i
        # calcula a linha i da matriz U
        for j in range(i, n): # para cada coluna j até a última
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # calcula a coluna i da matriz L
        for j in range(i+1, n): # para cada linha j da coluna i+1 até a última
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]
    
    return L, U

# Conseguimos decompor A em L e U, logo temos (L U)x = b,
# podemos entao resolver o problema em duas etapas, onde Ux = y, tendo assim Ly = b e Ux = y
# primeiro resolvemos ly = b, e depois ux = y

def foward_substitution(L, b): #calcula y resolvendo um sistema triangular inferior (substituiçao direta, forward substitution)
    # recebe uma matriz triangular inferior L e um vetor b e resolve o sistema Ly = b
    n = L.shape[0] # tamanho do vetor b
    y = np.zeros(n) # vetor solução y (usaremos depois para resolver Ux = y) 
    for i in range(n): 
        y[i] = b[i] - sum(L[i, k] * y[k] for k in range(i)) #y_i = (b_i - \sum_{k=1}^{i-1} L_{ik} * y_k)L_{ii}
    return y

def backward_substitution(U, y): #calcula x resolvendo um sistema triangular superior (substituiçao reversa, backward substitution)
    # recebe uma matriz triangular superior U e um vetor y e resolve o sistema Ux = y
    n = U.shape[0] # tamanho do vetor y
    x = np.zeros(n) # vetor solução x
    for i in range(n-1, -1, -1): # percorre o vetor y de trás para frente
        x[i] = (y[i] - sum(U[i, k] * x[k] for k in range(i+1, n))) / U[i, i] #x_i = (y_i - \sum_{k=i+1}^{n} U_{ik} * x_k)/U_{ii}
    return x

def solve_lu(A, b):
    # recebe uma matriz A e um vetor b e resolve o sistema Ax = b
    # retorna o vetor x solução
    L, U = lu_decomposition(A) # decompõe A em L e U
    y = foward_substitution(L, b) # resolve Ly = b
    x = backward_substitution(U, y) # resolve Ux = y
    return x

print("Teste 1")
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]])
b = np.array([3, 5, -1])
print("A:")
print(A)
print("b:")
print(b)
x = solve_lu(A, b)
print("x:")
print(x)
print("L:")
L, U = lu_decomposition(A)
print(L)
print("U:")
print(U)
print("Determinante de A:")
print(U.diagonal().prod())



Teste 1
A:
[[ 1  2  0]
 [ 1  3  1]
 [-2  0  1]]
b:
[ 3  5 -1]
x:
[1. 1. 1.]
L:
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  4.  1.]]
U:
[[ 1.  2.  0.]
 [ 0.  1.  1.]
 [ 0.  0. -3.]]
Determinante de A:
-3.0


**Assim temos resolvido $Ax = b$**

## Eliminaçao de Gauss

* Um metodo conhecido como (Escalonamento), nesse método podemos encontrar a matriz L e U. e resolver Ax=b

ele consiste em pensar que queremos para as matrizes

$\alpha + \alpha x = 0$ -> chamaremos esse x de m

$m = \frac{-linha}{pivo}$

$L_i <- L_i+m*l_{i-1}$