In [1]:
import numpy as np

## Eliminaçao de Gauss

* Um metodo conhecido como (Escalonamento), nesse método podemos encontrar a matriz L e U. e resolver Ax=b

ele consiste em pensar que queremos para as matrizes

$\alpha + \alpha x = 0$ -> chamaremos esse x de m

$m = \frac{-linha}{pivo}$

$L_i <- L_i+m*l_{i-1}$

In [14]:
#Metodo de eliminaçao de gauss

def gauss_elimination(A):
    n = len(A) # numero de linhas
    m = np.zeros((n,n)) # matriz m
    for i in range(n): # para cada linha queremos zerar sua coluna na nova matriz A
        for j in range(i, n): # para cada linha abaixo da linha i
            if j == i:
                fator = - 1
                m[j][i] = fator
                continue
            else:
                fator = - A[j][i]/A[i][i] # fator para zerar a coluna i
            for k in range(i, n): #Transformando a nova linha
                A[j][k] = A[j][k] + fator * A[i][k]
            m[j][i] = fator

    return m, A


A = np.array([[2, 1, 2], [4, 3, 3], [6, 5, -1]])
M, A = gauss_elimination(A)

#multiplicando os elementos de M por (-1 ) para obter L 
L = -M
U = A

print("L:")
print(L)
print("U:")
print(U)

L:
[[ 1. -0. -0.]
 [ 2.  1. -0.]
 [ 3.  2.  1.]]
U:
[[ 2  1  2]
 [ 0  1 -1]
 [ 0  0 -5]]
