In [1]:
import numpy as np

In [2]:

def backward_substitution(U, y): #calcula x resolvendo um sistema triangular superior (substituiçao reversa, backward substitution)
    # recebe uma matriz triangular superior U e um vetor y e resolve o sistema Ux = y
    n = U.shape[0] # tamanho do vetor y
    x = np.zeros(n) # vetor solução x
    for i in range(n-1, -1, -1): # percorre o vetor y de trás para frente
        x[i] = (y[i] - sum(U[i, k] * x[k] for k in range(i+1, n))) / U[i, i] #x_i = (y_i - \sum_{k=i+1}^{n} U_{ik} * x_k)/U_{ii}
    return x

## Eliminaçao de Gauss

* Um metodo conhecido como (Escalonamento), nesse método podemos encontrar a matriz L e U. e resolver Ax=b

ele consiste em pensar que queremos para as matrizes

$\alpha + \alpha x = 0$ -> chamaremos esse x de m

$m = \frac{-linha}{pivo}$

$L_i <- L_i+m*l_{i-1}$

In [3]:
#Metodo de eliminaçao de gauss

def gauss_elimination(A, b):
    n = len(A) # numero de linhas
    m = np.zeros((n,n)) # matriz m
    for i in range(n): # para cada linha queremos zerar sua coluna na nova matriz A
        
        indice = i + np.argmax(np.abs(A[i:, i]))
        A[[i, indice]] = A[[indice, i]]
        b[[i, indice]] = b[[indice, i]]

        for j in range(i+1, n): # para cada linha abaixo da linha i
            fator = - A[j][i]/A[i][i] # fator para zerar a coluna i
            for k in range(i, n): #Transformando a nova linha
                A[j][k] = A[j][k] + fator * A[i][k]
            b[j] = b[j] + fator * b[i]
            m[j][i] = fator

    return m, A, b


A = np.array([[0.0, 1.0, 2.0], [1.0, -1.0, 3.0], [-2.0, 3.0, 1.0]])
b = np.array([8.0, 8.0, 7.0])

M, U, b = gauss_elimination(A, b)

print("U:")
print(U)
print("b:")
print(b)

def solve_x(A, b):
    # recebe uma matriz A e um vetor b e resolve o sistema Ax = b
    # retorna o vetor x solução
    
    x = backward_substitution(U, b) # resolve Ux = y
    return x

print("x:")
print(solve_x(A, b)) # resolve Ax = b

U:
[[-2.   3.   1. ]
 [ 0.   1.   2. ]
 [ 0.   0.   2.5]]
b:
[7.  8.  7.5]
x:
[1. 2. 3.]
