In [2]:
import numpy as np

# PA

PA parte da eliminaçao de gauss com pivoteamento, no caso, para encontrar as matrizes U e L apos fazer a troca de linhas que realizamos, ou seja:

$PA = LU$ para isso partimos de pontos semelhantes do codigo anterior

a matriz P é a matriz identidade permutada onde houve permutacoes durante a eliminaçao

In [ ]:
#Metodo de eliminaçao de gauss com PA


def gauss_elimination(A, b):
    n = len(A) # numero de linhas
    P = np.eye(n)
    L = np.eye(n)
    
    for i in range(n-1): # para cada linha queremos zerar sua coluna na nova matriz A
        #escolha do pivo
        indice = i + np.argmax(np.abs(A[i:, i]))
        #Troca de linhas em A, b, P e se i>0 nas colunas antigas de L
        if(indice != i):
            A[[i, indice]] = A[[indice, i]]
            b[[i, indice]] = b[[indice, i]]
            P[[i, indice]] = P[[indice, i]] #troca na matriz de permutacao
            if (i > 0):
                L[[i, indice], :i] = L[[indice, i], :i]
        
        #Eliminacao
        for j in range(i+1, n): # para cada linha abaixo da linha i
            fator = - A[j][i]/A[i][i] # fator para zerar a coluna i
            A[j, i:] = A[j,i:] + fator * A[i,i:] #transformando a nova linha
            b[j] = b[j] + fator * b[i]
            L[j][i] = -fator

    U = A # A final é a triangular superior
    return L, U, P, b 


A = np.array([[0.0, 1.0, 2.0], [1.0, -1.0, 3.0], [-2.0, 3.0, 1.0]], dtype=float)
b = np.array([8.0, 8.0, 7.0],dtype=float)

L, U, P, b_final = gauss_elimination(A.copy(), b.copy())

print("Matriz L:")
print(L)
print("Matriz U:")
print(U)
print("Matriz P:")
print(P)
 
# Verificando se P A ≈ L U
PA = P @ A
LU = L @ U
print("P @ A  =\n", PA)
print("L @ U  =\n", LU)

print("Diferença (P A - L U):\n", PA - LU)


Matriz L:
[[ 1.   0.   0. ]
 [-0.   1.   0. ]
 [-0.5  0.5  1. ]]
Matriz U:
[[-2.   3.   1. ]
 [ 0.   1.   2. ]
 [ 0.   0.   2.5]]
Matriz P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
P @ A  =
 [[-2.  3.  1.]
 [ 0.  1.  2.]
 [ 1. -1.  3.]]
L @ U  =
 [[-2.  3.  1.]
 [ 0.  1.  2.]
 [ 1. -1.  3.]]
Diferença (P A - L U):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
